import type { ProjectHealth, ChangeEvent, MilestoneInfo, RiskSummary } from '@/stores/useDashboardStore';

/**
 * Sample dashboard data for development and testing
 * This simulates a realistic IT portfolio scenario
 */

export const sampleProjectHealth: ProjectHealth[] = [
  {
    id: '1',
    name: 'RPM Dashboard & CRC 数据接入',
    owner: 'Alice Chen',
    progressPercent: 78,
    doneTasks: 12,
    totalTasks: 15,
    status: 'on_track',
    nextMilestone: {
      name: 'MS1: Design Complete',
      date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'on_track',
    },
    blockerCount: 0,
    highRiskCount: 1,
  },
  {
    id: '2',
    name: 'Security Audit & Compliance',
    owner: 'Bob Smith',
    progressPercent: 54,
    doneTasks: 7,
    totalTasks: 13,
    status: 'at_risk',
    nextMilestone: {
      name: 'MS2: Beta Release',
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'overdue',
    },
    blockerCount: 1,
    highRiskCount: 2,
  },
  {
    id: '3',
    name: 'Cloud Migration Phase 1',
    owner: 'Carol Wang',
    progressPercent: 23,
    doneTasks: 3,
    totalTasks: 13,
    status: 'blocked',
    nextMilestone: {
      name: 'MS3: Security Sign-off',
      date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'at_risk',
    },
    blockerCount: 2,
    highRiskCount: 3,
  },
  {
    id: '4',
    name: 'API Gateway Redesign',
    owner: 'David Lee',
    progressPercent: 92,
    doneTasks: 11,
    totalTasks: 12,
    status: 'on_track',
    nextMilestone: {
      name: 'MS4: Production Deploy',
      date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'on_track',
    },
    blockerCount: 0,
    highRiskCount: 0,
  },
  {
    id: '5',
    name: 'Data Lake Integration',
    owner: 'Emma Zhang',
    progressPercent: 45,
    doneTasks: 9,
    totalTasks: 20,
    status: 'at_risk',
    nextMilestone: {
      name: 'MS5: Data Pipeline',
      date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'at_risk',
    },
    blockerCount: 0,
    highRiskCount: 2,
  },
  {
    id: '6',
    name: 'Mobile App Refactor',
    owner: 'Frank Miller',
    progressPercent: 67,
    doneTasks: 8,
    totalTasks: 12,
    status: 'on_track',
    nextMilestone: {
      name: 'MS6: UX Review',
      date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'on_track',
    },
    blockerCount: 0,
    highRiskCount: 1,
  },
  {
    id: '7',
    name: 'Legacy System Deprecation',
    owner: 'Grace Kim',
    progressPercent: 15,
    doneTasks: 2,
    totalTasks: 15,
    status: 'critical',
    nextMilestone: {
      name: 'MS7: User Migration',
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'overdue',
    },
    blockerCount: 1,
    highRiskCount: 4,
  },
];

export const sampleChangeFeed: ChangeEvent[] = [
  {
    id: '1',
    type: 'completed',
    entityType: 'Item',
    entityId: '123',
    entityName: 'Task "API Design"',
    projectName: 'RPM Dashboard & CRC 数据接入',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    details: 'Status changed to Done',
  },
  {
    id: '2',
    type: 'updated',
    entityType: 'Item',
    entityId: '124',
    entityName: '"Sprint 3"',
    projectName: 'Security Audit & Compliance',
    timestamp: new Date(Date.now() - 23 * 60 * 1000).toISOString(),
    details: 'Dates changed from Jan 25 to Jan 28',
  },
  {
    id: '3',
    type: 'conflict',
    entityType: 'Item',
    entityId: '125',
    entityName: '"QA Plan"',
    projectName: 'Security Audit & Compliance',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    details: 'Conflict detected: File sync version differs from local',
  },
  {
    id: '4',
    type: 'created',
    entityType: 'Item',
    entityId: '126',
    entityName: '"Security Audit" issue',
    projectName: 'RPM Dashboard & CRC 数据接入',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    details: 'New issue created with High priority',
  },
  {
    id: '5',
    type: 'sync',
    entityType: 'Project',
    entityId: '1',
    entityName: 'project-alpha.xml',
    projectName: 'RPM Dashboard & CRC 数据接入',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    details: '15 items updated from file sync',
  },
  {
    id: '6',
    type: 'updated',
    entityType: 'Item',
    entityId: '127',
    entityName: '"Database Schema"',
    projectName: 'Data Lake Integration',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    details: 'Added new columns for metadata',
  },
  {
    id: '7',
    type: 'completed',
    entityType: 'Item',
    entityId: '128',
    entityName: 'Milestone "Phase 1 Complete"',
    projectName: 'API Gateway Redesign',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    details: 'Milestone marked as complete',
  },
  {
    id: '8',
    type: 'created',
    entityType: 'Item',
    entityId: '129',
    entityName: '"Performance bottleneck" issue',
    projectName: 'Cloud Migration Phase 1',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    details: 'New Critical issue created',
  },
];

export const sampleMilestones: MilestoneInfo[] = [
  {
    id: '1',
    name: 'MS1: Design Complete',
    projectName: 'RPM Dashboard & CRC 数据接入',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'on_track',
  },
  {
    id: '2',
    name: 'MS2: Beta Release',
    projectName: 'Security Audit & Compliance',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'overdue',
  },
  {
    id: '3',
    name: 'MS3: Security Sign-off',
    projectName: 'RPM Dashboard & CRC 数据接入',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'at_risk',
  },
  {
    id: '4',
    name: 'MS4: Production Deploy',
    projectName: 'API Gateway Redesign',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'on_track',
  },
  {
    id: '5',
    name: 'MS5: Data Pipeline',
    projectName: 'Data Lake Integration',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'at_risk',
  },
];

export const sampleRiskSummary: RiskSummary = {
  critical: 2,
  high: 5,
  medium: 12,
  low: 8,
};
